### ISSUE TITLE
Potentially broken links

### ISSUE THREAD

**Issue by GintasS** [pittcsc/Summer2022-Internships#310]
I am back 🍡 

Error: https://careers.point72.com/CSJobDetail?jobName=2021-cubist-software-engineering-internship-program&jobCode=CSS-0004136 on line 145 is unreachable.
Error: https://www.mongodb.com/careers/jobs/2309781 on line 146 is unreachable.
Error: https://jobs.bnymellon.com/jobs/2007833 on line 79 is unreachable.
Error: https://jobs.intel.com/page/show/search-results#q=2021&t=Jobs&sort=relevancy&layout=table&f:@countryfullname=[United%20States]&f:@employeetype=[Intern%2FStudent] on line 258 is unreachable.
Error: https://careers.ibm.com/ShowJob/Id/961980/Back-End-Developer-Summer-Intern-2021/?lang=en on line 78 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?PageType=JobDetails&partnerid=25239&siteid=5014&jobid=6674182#jobDetails=6674182_5014 on line 166 is unreachable.
Error: https://jobs.lever.co/anduril/9312d9f4-ce3b-43b8-b870-d86bfc838135 on line 142 is unreachable.
Error: https://jobs.lever.co/kensho/312ae842-2798-4021-b76f-33e11c504d71 on line 216 is unreachable.
Error: https://careers.tiktok.com/position?project=6854152751179303182&type=3&current=1&limit=100 on line 17 is unreachable.
Error: https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25008&siteid=5131&PageType=searchResults&SearchType=linkquery&LinkID=6166#keyWordSearch=&locationSearch=&Function%20Category=Information%20Technology%20(IT on line 329 is unreachable.
Error: https://jobs.lever.co/smithmicro/47b315f1-e798-4139-abd1-35da544a02b3/apply on line 240 is unreachable.
Error: https://careers.caci.com/ListJobs?keyword=2021&&Page=1&SortOrder=desc&SortField=AddedOn on line 325 is unreachable.
Warning: https://jobs.apple.com/en-us/search?location=united-states-USA&team=internships-STDNT-INTRN on line 14 contains a country code.
Error: https://jobs.lever.co/anduril/d15840b6-081b-4d4c-95ed-008d681b4f7f/apply on line 142 is unreachable.
Error: https://jobs.lever.co/kensho/f1d84d9a-c754-4f7f-97d4-b87443fb2e60 on line 216 is unreachable.
Error: https://jobszp1.lanl.gov/OA_HTML/OA.jsp?page=/oracle/apps/irc/candidateSelfService/webui/VisVacDispPG&OAHP=IRC_EXT_SITE_VISITOR_APPL&OASF=IRC_VIS_VAC_DISPLAY&akRegionApplicationId=821&transactionid=1759536200&retainAM=N&addBreadCrumb=RP&p_svid=81425&p_spid=3628350 on line 70 is unreachable.
Error: https://career.bayer.us/en/job/data-engineer-intern--SF263281 on line 312 is unreachable.
Error: https://penfed.dejobs.org/mclean-va/quantitative-and-data-analytics-intern-summer-2021/0C1C9EA4403B4F969913C8F91D24483E/job/ on line 354 is unreachable.
Error: https://penfed.dejobs.org/mclean-va/it-intern-summer-2021/D6198D2D61D8468B8D2B592A18E379A6/job/ on line 354 is unreachable.
Error: https://careers.petsmart.com/student-interns/jobs/2162?lang=en-us on line 391 is unreachable.
Error: https://careers.petsmart.com/student-interns/jobs?keywords=Software&page=1&sortBy=relevance&categories=Students on line 391 is unreachable.
Error: https://www.bms.com/ca/en/job-seekers/job-search-results.html?country=united%20states%20of%20america&category=intern/co-op/student/flex&keyword=2021&page=1 on line 402 is unreachable.
Error: https://careers.perspecta.com/jobs?keywords=2021&page=1 on line 401 is unreachable.
Error: https://careers-avexis.icims.com/jobs/5543/internship%2c-information-technology-%28illinois%29/job?in_iframe=1 on line 441 is unreachable.
Error: https://careers-avexis.icims.com/jobs/5544/internship%2c-information-technology-%28colorado%29/job?in_iframe=1 on line 441 is unreachable.
Error: https://jobs.postholdings.com/job/minnetonka/it-support-analyst-internship-summer-2021/8462/1385263616 on line 440 is unreachable.
Error: https://jobs.postholdings.com/job/minnetonka/it-business-intelligence-internship-summer-2021/8462/1385263808 on line 440 is unreachable.
Warning: https://www.esri.com/en-us/about/careers/job-search?q=2021 on line 478 contains a country code.
Error: https://careers.bakerhughes.com/global/en/search-results?keywords=2021 on line 492 is unreachable.
Error: https://www.esri.com/careers/information-technology-2021-internships-13005 on line 478 is unreachable.
Error: https://bairdcareers.com/career-search/?keyword=2021&zip=&distance=20.0&country=United%20States%20of%20America&state=&office=&career_areas=&spage=1 on line 454 is unreachable.
Error: https://www.edisoncareers.com/ShowJob/Id/990886/2021-Summer-Internship-IT-Computer-Science,-Computer-Engineering,-Electrical-Engineering-Majors/sce-brand/sce on line 515 is unreachable.
Error: https://salesforce.wd1.myworkdayjobs.com/Futureforce_Internships/1/refreshFacet/318c8bb6f553100021d223d9780d30be on line 94 is unreachable.
Error: https://boards.greenhouse.io/perch1/jobs/4867481002 on line 547 is unreachable.
Error: https://careers.vmware.com/main/jobs?keywords=2021&page=1&sortBy=relevance&location=United%20States&woe=12&stretchUnit=MILES&stretch=50 on line 541 is unreachable.
Error: https://careers.mcafee.com/job/plano/cybersecurity-technical-support-engineer-intern/731/17956783 on line 569 is unreachable.
Error: https://careers.hcss.com/data-analyst-intern_2461513/ on line 583 is unreachable.
Error: https://jobs.drivetime.com/jobs?page_size=50&page_number=1&keyword=Internship&sort_by=score&sort_order=DESC on line 581 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25053&siteid=5248&PageType=JobDetails&jobid=1445244 on line 590 is unreachable.
Error: https://jobs.lever.co/enthought/cf87b6ce-77a6-465d-afeb-1280343d417a on line 613 is unreachable.
Error: https://jackhenry.avature.net/careers/SearchJobs/2021?jobRecordsPerPage=6& on line 587 is unreachable.
Error: https://jobs.lever.co/bill/c9603d02-9526-4d36-be1a-9792deec29e5 on line 634 is unreachable.
Error: https://devtechnology.com/careers/ on line 663 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25091&siteid=5105&PageType=JobDetails&jobid=702696 on line 646 is unreachable.
Error: https://go.wepay.com/posting/?jobId=97bfaef8-56ab-419d-afb9-007256b5f38c on line 658 is unreachable.
Error: https://jobs.siemens.com/healthineers/jobs?page=1&keywords=2021&sortBy=relevance&location=United%20States&woe=12&stretchUnit=MILES&stretch=0 on line 656 is unreachable.
Error: https://jobs.lever.co/opendoor/13723d39-e96d-48aa-b414-eaa24e9f5b74/apply?lever-origin=applied&lever-source%5B%5D=BuiltInSan%20Francisco on line 665 is unreachable.
Error: https://jobs.lever.co/fiscalnote/d7bec0af-d2df-4621-a568-8f3e0d6f71fb/apply on line 666 is unreachable.
Error: https://www.henkel.com/careers/jobs-and-application/1139612-1139612 on line 687 is unreachable.
Error: https://jobs.lever.co/ro/92598b00-3ccc-43b8-aff2-21b7add3d0ce on line 672 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=643956#jobDetails=643956_5661 on line 677 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=643964#jobDetails=643964_5661 on line 677 is unreachable.
Error: https://sjobs.brassring.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=26513&siteid=5661&PageType=JobDetails&jobid=644341 on line 677 is unreachable.
Error: https://jobs.lever.co/secondspectrum/47e1b768-0f6b-4760-8c40-c5f69062c867/apply on line 681 is unreachable.
Error: https://jobs.bmoharris.com/us/en/search-results?keywords=2021 on line 614 is unreachable.
Error: https://findjobs.statefarm.com/ShowJob/Id/460685/Intern%20%20%20Technology on line 174 is unreachable.
Error: https://quantumsignalai.com/internships/ on line 704 is unreachable.
Error: https://www.cqlcorp.com/careers/software-developer-internship/ on line 683 is unreachable.
Error: https://jobs.lever.co/nylas/36dbc87f-937f-41dc-ab36-c371d6e8acee on line 702 is unreachable.
Error: https://www.amobee.com/company/careers/internship-summer-2021-software-engineering-data-science-2/ on line 713 is unreachable.
Error: https://careers.adtalem.com/us/en/job/116404/Summer-Intern-Analytics-2021 on line 701 is unreachable.
Error: https://github.com/hjs2000cn on line 749 is unreachable.
Error: https://github.com/aidev1065 on line 808 is unreachable.
Error: https://jobs.jobvite.com/quantum-health/job/ocFfefw4 on line 729 is unreachable.
Error: https://jobs.jobvite.com/quantum-health/job/opwfefw8 on line 729 is unreachable.
Error: https://jobs.jobvite.com/careers/siriusxm/job/ojxEdfwr/apply on line 343 is unreachable.
Error: https://jobs.jobvite.com/quantum-health/job/oUxfefwE on line 729 is unreachable.
Error: https://jobs.jobvite.com/syncroness/job/oKVhefwU on line 719 is unreachable.
Error: https://jobs.jobvite.com/chobani/job/ooegefwQ on line 735 is unreachable.
Error: https://jackhenry.avature.net/careers/JobDetail/iPay-Software-Engineer-Intern-2021/8409 on line 587 is unreachable.
Error: https://jackhenry.avature.net/careers/JobDetail/Network-Engineer-Intern-2021/8466 on line 587 is unreachable.
Error: https://bairdcareers.com/career-search/posting/internship---it-service-desk-year-round-/8218BR/ on line 454 is unreachable.
Error: https://careers.boozallen.com/careers/JobDetail/Annapolis-Junction-Data-Science-Intern-R0091880/31448?uid=5FioJR6DtYxLDT2g on line 378 is unreachable.
Error: https://careers.boozallen.com/careers/JobDetail/Annapolis-Junction-Data-Science-Intern-R0091880/31448?uid=5FioJR6DtYxLDT2g on line 378 is unreachable.
Error: https://bairdcareers.com/career-search/posting/internship---compliance-data-analytics-year-round-immediate-start-/8270BR on line 454 is unreachable.
Error: https://bairdcareers.com/career-search/posting/internship---it-software-developer-year-round-/8220BR on line 454 is unreachable.
Error: https://findjobs.statefarm.com/Listjobs/All/search/keyword/Intern on line 416 is unreachable.
Error: https://findjobs.statefarm.com/ShowJob/JobId/458399/InternTechnologyRDCSummer2021 on line 416 is unreachable.
Error: https://findjobs.statefarm.com/ShowJob/JobId/465285/InternEDAPreMAGNetProgramUniversityofGeorgiaSummer2021 on line 416 is unreachable.
Error: https://careers.fcagroup.com/job/11390451/2021-information-technology-intern-digital-technology-leader-auburn-hills-mi/ on line 694 is unreachable.

**Comment by Zmwang622** [comment]
HES BACK!!!!

**Comment by Zmwang622** [comment]
do you think you could implement some sort of auto link checker? I know you mentioned it before
