### ISSUE TITLE
Add link to form for subscription to README

### ISSUE THREAD

**Issue by MrHakimov** [pittcsc/Summer2022-Internships#338]

**Comment by GintasS** [comment]
@Zmwang622 Are you guys still sending the newsletters every week, X day or is this issue about something else?

**Comment by Zmwang622** [comment]
We used to have the newsletter but ran into issues where it got to large so Gmail wouldn't send them and I didn't want to pay for Sendgrid

**Comment by GintasS** [comment]
So should we close this or is it worth it to investigate a workaround, such as sending multiple emails from Gmail below the threshold (5 emails x 1000 recipients for example) or some other method?

**Comment by Zmwang622** [comment]
I think we should close it, imo the README file is fine by itself
