### ISSUE TITLE
Link for Cockroach Labs Doesn't Work

### ISSUE THREAD

**Issue by JDaniel41** [pittcsc/Summer2022-Internships#340]
The link for [Cockroach Labs](https://www.cockroachlabs.com/careers/job/?gh_jid=3067803) is a broken link

**Comment by monishshah18** [comment]
> The link for [Cockroach Labs](https://www.cockroachlabs.com/careers/job/?gh_jid=3067803) is a broken link

I believe there are no current openings. hence broken link. I suggest we should remove Cockroach Labs for now.

**Comment by EParmar18** [comment]
Removed the link, will add it back once a position opens up
