### ISSUE TITLE
Broken Apple Link 

### ISSUE THREAD

**Issue by SPahooja** [pittcsc/Summer2022-Internships#354]
The link for Apple internships seems to be broken : 
![image](https://user-images.githubusercontent.com/55768732/123520534-d3cd8280-d6ce-11eb-8100-85d5bccf66a0.png)

**Comment by monishshah18** [comment]
> The link for Apple internships seems to be broken :
> ![image](https://user-images.githubusercontent.com/55768732/123520534-d3cd8280-d6ce-11eb-8100-85d5bccf66a0.png)

Yes, it seems applications are closed for this role now.

**Comment by Zmwang622** [comment]
Forgot to mention, for future closed postings lets try to maintain this style: 
![image](https://user-images.githubusercontent.com/36709118/123730487-6c493b80-d864-11eb-990f-2825566cdad4.png)
 rather than outright deleting the row
