### ISSUE TITLE
Including internships with poor websites

### ISSUE THREAD

**Issue by GintasS** [pittcsc/Summer2022-Internships#364]
I have found this internship position: [here](https://careers-federatedinsurance.icims.com/jobs/3098/it-systems-developer-intern---summer-2022/job?mode=job&iis=SOURCE&iisn=LinkedIn&mobile=false&width=1887&height=500&bga=true&needsRedirect=false&jan1offset=120&jun1offset=180), but the website is very poor (probably css is not loading or other issues). Should we include this or not, because  it can look like a scam :D

![image](https://user-images.githubusercontent.com/20372363/124352587-c4d45c00-dc09-11eb-99d0-7b50b39cdbbc.png)

**Comment by Zmwang622** [comment]
Looks like CSS isn't loading. The site looks good on my end 
![image](https://user-images.githubusercontent.com/36709118/124361318-7ec4cb80-dbfc-11eb-9bf1-596d3b4c5b89.png)

**Comment by GintasS** [comment]
Ok then, will include this internship.
