### ISSUE TITLE
Including a position with limited IT work

### ISSUE THREAD

**Issue by GintasS** [pittcsc/Summer2022-Internships#365]
I have found this position:

Should I include it or not? Since this position has a very limited IT work?

|[The Cincinnati Insurance Companies](https://cinfin.taleo.net/careersection/ex/jobdetail.ftl?job=2100296&tz=GMT%2B03%3A00s)| Fairfield, OH | Actuarial Summer Internship |

![image](https://user-images.githubusercontent.com/20372363/124352687-8db27a80-dc0a-11eb-9052-0e74ed715d7b.png)

**Comment by Zmwang622** [comment]
My vote is no. Actuary is a whole separate field from SWE/IT

**Comment by GintasS** [comment]
Ok thanks, closing this one.
