### ISSUE TITLE
Oracle Opening is not General.

### ISSUE THREAD

**Issue by monishshah18** [pittcsc/Summer2022-Internships#377]
Oracle Opening is not General. It limits applicant to be at specific location. Still do we need to add that or any Note should be there?

**Comment by Zmwang622** [comment]
Yeah we should probably remove it

**Comment by Zmwang622** [comment]
let me check

**Comment by GintasS** [comment]
Added a note:

![image](https://user-images.githubusercontent.com/20372363/125597640-f957104b-6d36-4d3a-a3a2-a2c6d82e2369.png)

Is this correct? Can we close this issue?
