### ISSUE TITLE
Audible internship is closed

### ISSUE THREAD

**Issue by logangeorge01** [pittcsc/Summer2022-Internships#381]
Would open a pr but don't know what the right format for closing an internship is

**Comment by Zmwang622** [comment]
thanks!

**Comment by Jashann** [comment]
Could you tell when most internships close I need to make resume yet.

**Comment by Zmwang622** [comment]
March

**Comment by Jashann** [comment]
Really I meant Summer internships, March is too late

**Comment by jameszhang-a** [comment]
@Jashann Pretty sure many/some companies will still be hiring by March.
