### ISSUE TITLE
Feature: Discussion Section

### ISSUE THREAD

**Issue by harsohailB** [pittcsc/Summer2022-Internships#397]
I think it would useful to have a discussion for the repo to talk about applications, callbacks, interviews, and basically everybody's experience with the listings posted here.

Docs: <a href="https://docs.github.com/en/discussions">GitHub Discussion</a>

Example:
![image](https://user-images.githubusercontent.com/47438886/126819767-c928b48d-d078-4e01-ad47-1da82560d37a.png)

**Comment by byfnoel** [comment]
I support this request.

**Comment by GintasS** [comment]
Definitely yes! But as all new things come, someone will need to actively moderate it :)

**Comment by Zmwang622** [comment]
Oh fuck yes, I'll look into seeing if anyone wants to moderate

**Comment by Zmwang622** [comment]
#414 , I started!
