### ISSUE TITLE
Salesforce link broken

### ISSUE THREAD

**Issue by logangeorge01** [pittcsc/Summer2022-Internships#398]
General SWE internships might be closed. They have one for their Tableau subsidiary [here](https://salesforce.wd1.myworkdayjobs.com/en-US/Futureforce_Internships/job/Washington---Seattle/Summer-2022-Intern---Tableau-Software-Engineer_JR103736-1?d=cta-summer-view-sjb-1) though

**Comment by brandon-m-wang** [comment]
seems like workday is just down

**Comment by logangeorge01** [comment]
That's ironic but it is closed, just check tomorrow

**Comment by BenjaminCHEN2016** [comment]
Seems it is indeed closed...

**Comment by monishshah18** [comment]
Please create a PR for Closed internship if it seems closed.

**Comment by GintasS** [comment]
Yes, the Tableu Internship is still there. @monishshah18 can you add it instead? [link](https://salesforce.wd1.myworkdayjobs.com/en-US/Futureforce_Internships/job/Washington---Seattle/Summer-2022-Intern---Tableau-Software-Engineer_JR103736-1?d=cta-summer-view-sjb-1)

**Comment by monishshah18** [comment]
@GintasS Tableu is already added. If you navigate little below separately.

**Comment by GintasS** [comment]
@monishshah18 No no, Salesforce has it's own Tableu intern position:
[link](https://salesforce.wd1.myworkdayjobs.com/en-US/Futureforce_Internships/job/Washington---Seattle/Summer-2022-Intern---Tableau-Software-Engineer_JR103736-1?d=cta-summer-view-sjb-1)

Can you add this instead of closing the position.

**Comment by monishshah18** [comment]
@GintasS Both Salesforce and Tableu has same Job Id for the Intern Role. Both has Job Id: **JR103736**. They are being redirected to same url. So either we close salesforce as I did in this PR or we can remove tableu and move it to Salesforce.
Do let me know what you feel the best?

**Comment by GintasS** [comment]
@monishshah18 Fair enough, sorry for this misunderstanding, thought Salesforce and Tableu are completely different companies :) Closing this issue and merging your PR.
