### ISSUE TITLE
Adding Software Engineering Internship for Women - Summer 2022 position

### ISSUE THREAD

**Issue by GintasS** [pittcsc/Summer2022-Internships#405]
I have found this position, but not sure if we should include this. Historically women are not really represented in IT field, but in that case some other groups could also fall into that category. Should we make an exception here? Or we should stay clear of any gender/race/etc related positions?

Job [link](https://careers.peak6.com/jobs/campus/chicago-il-united-states/software-engineering-internship-for-women-summer-2022/3343572?gh_jid=3343572#/)

**Comment by Zmwang622** [comment]
Add it and include the note about it's for women only!
