### ISSUE TITLE
Regarding Duplicate JP Morgan & Chase

### ISSUE THREAD

**Issue by monishshah18** [pittcsc/Summer2022-Internships#416]
There are 2 entries for JP Morgan. Both are correct. One consists of all 2022 internships opportunities and other pointing towards single SWE Internship role. Should we remove one or merge both? Also, one note to keep as since these roles require US Citizen so we need to mention that too.

**Comment by Zmwang622** [comment]
I'd rather just point to the SWE Internship role because that's the most relevant, but merging them both is a good idea
