### ISSUE TITLE
Johnson Controls' application is closed

### ISSUE THREAD

**Issue by qc542** [pittcsc/Summer2022-Internships#604]
The page reads, "Unfortunately this position has been closed but you can search our 4,584 open jobs by clicking here."

**Comment by Zmwang622** [comment]
![image](https://user-images.githubusercontent.com/36709118/132075245-44ff31e8-25d6-42f5-8d79-84192fa534df.png)
open for me

**Comment by qc542** [comment]
See the second paragraph of the posting. Also, there's no "apply" button anywhere on the page.
