### ISSUE TITLE
amazon Big Data intern closed 

### ISSUE THREAD

**Issue by moaz-eldefrawy** [pittcsc/Summer2022-Internships#656]
[Link](https://www.amazon.jobs/en/jobs/1673627/summer-2022-software-development-engineer-intern-big-data) is inactive.

**Comment by hkjava6** [comment]
Link is inactive

**Comment by moaz-eldefrawy** [comment]
I am sorry. Check the [link](https://www.amazon.jobs/en/jobs/1673627/summer-2022-software-development-engineer-intern-big-data) I left again. it's inactive. 

this is the same link that's posted in here with "Big Data "label". I am assuming you should remove or mark it.

![del](https://user-images.githubusercontent.com/24529552/132996254-b6683202-706a-4572-a5c6-9dd6d894461c.png)

**Comment by GintasS** [comment]
Removed it.
