### ISSUE TITLE
A number of job openings have already been closed

### ISSUE THREAD

**Issue by 94rain** [pittcsc/Summer2022-Internships#752]
I ran a check for all links in the readme and found the following broken links. Some are already closed, but for others, it is possible that there are still openings but the companies used another link instead and need confirmation.

[✖] https://jobs.target.com/job/brooklyn-park/software-engineering-internship-summer-2022/1118/13300878224 → Status: 0
[✖] https://jobs.cigna.com/us/en/job/21012002/Cigna-Technology-Early-Career-Development-Program-TECDP-Summer-Intern-2022-Evergreen → Status: 410
[✖] https://phh.tbe.taleo.net/phh02/ats/careers/v2/viewRequisition?org=BRACEBRIDGE_CAPITAL&cws=41&rid=246 → Status: 500
[✖] https://careers-federatedinsurance.icims.com/jobs/3098/it-systems-developer-intern---summer-2022/job?mode=job&iis=SOURCE&iisn=LinkedIn&mobile=false&width=1887&height=500&bga=true&needsRedirect=false&jan1offset=120&jun1offset=180 → Status: 410
[✖] https://careers.usventure.com/us/en/job/USVEUSREQ007946/Software-Engineering-Intern → Status: 410
[✖] https://www.janestreet.com/join-jane-street/position/5416966002/ → Status: 404
[✖] https://www.dickssportinggoods.jobs/jobs/13316339/2022-corporate-internships-training-programs-pre-application-coraopolis-pa/?src=11663 → Status: 404
[✖] https://jobs.rsmus.com/ShowJob/JobId/498233/2022SummerConsultingInternTechnologyBusinessAppsNAV → Status: 404
[✖] https://careers-virginorbit.icims.com/jobs/6289/2022-summer-internship---multiple-departments/job?mobile=false&width=1168&height=500&bga=true&needsRedirect=false&jan1offset=-480&jun1offset=-420 → Status: 410
[✖] https://jobs.lever.co/hyperscience/c136b270-1682-4ac7-82d8-83992b596d6c → Status: 404
[✖] https://careers-us.garmin.com/us/en/job/21001G1/Software-Engineer-Intern-Mobile-HQ-Olathe-KS → Status: 410
[✖] https://jobs.lever.co/aechelon/0d491d1a-4e50-4380-950c-41eef676acda/apply → Status: 404
[✖] https://jobs.td.com/en/job/13581186/2022-summer-analyst-software-engineer-new-york-ny/ → Status: 404
[✖] https://jobs.jnj.com/jobs/2105956194W?lang=en-us&previousLocale=en-US → Status: 0
[✖] https://careers.peraton.com/job-details/13556879/systems-software-engineering-intern-chantilly-va/#job-description → Status: 404
[✖] https://www.amazon.jobs/en/jobs/1650024/software-development-engineer-intern-amazon-robotics-summer-2022 → Status: 404
[✖] https://www.wellsfargojobs.com/job/des-moines/2022-wells-fargo-technology-internship-program/1251/13073149088 → Status: 0
[✖] https://jobs.lever.co/broadwaytechnology/2048b077-9404-4ab0-8dc9-9022ab90a711 → Status: 404
[✖] https://jobs.smartrecruiters.com/FireEyeInc1/743999768661855 → Status: 400
[✖] https://jobs.smartrecruiters.com/FireEyeInc1/743999768673869 → Status: 400
[✖] https://jobs.smartrecruiters.com/FireEyeInc1/743999768674573 → Status: 400
[✖] https://careers-chickfila.icims.com/jobs/10180/2022-digital-transformation-and-technology-summer-intern/job → Status: 410
[✖] https://www.uber.com/global/en/careers/list/107068/ → Status: 406
[✖] https://university-uber.icims.com/jobs/107178/job?mobile=false&width=1030&height=500&bga=true&needsRedirect=false&jan1offset=-360&jun1offset=-300 → Status: 410
[✖] https://jobs.microfocus.com/global/en/job/7021218/Systems-Software-Engineer-Intern-at-Vertica-Summer-2022 → Status: 410
[✖] https://boards.greenhouse.io/embed/job_app?token=3461147&gh_src=dbd19ebc1&s=LinkedIn&source=LinkedIn → Status: 404
[✖] https://jobs.lumen.com/global/en/job/262143/Intern-Software-Engineer-Summer-2022-CO-or-Remote-US → Status: 410

**Comment by owini** [comment]
Will look into this--thanks!

**Comment by 94rain** [comment]
fixed by #775
