### ISSUE TITLE
Suggestion: either a filter to see opportunities for India or another fork that has India based internships

### ISSUE THREAD

**Issue by thesachinsingh** [pittcsc/Summer2022-Internships#771]
It would be really useful to see internships/co-ops for countries other than US/Canada as well.
PS : I personally want the ones from India, i have a lot of friends who've been looking for the same. 🥺

**Comment by EParmar18** [comment]
Hi Sachin, I think our main goal for this repo is to provide the internships/co-ops for main US-based college students but feel free to create a fork/repo focused on non-NA positions!

**Comment by thesachinsingh** [comment]
> Hi Sachin, I think our main goal for this repo is to provide the internships/co-ops for mainly US-based college students but feel free to create a fork/repo focused on non-NA positions!

Gotcha, Thanks mate
